JqueryDTWithMVC/Models/DAL/Vacation/VacationsModel.cs
using JqueryDTWithMVC.Models.DAL.Branches;
using JqueryDTWithMVC.Models.DAL.VacationType;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace JqueryDTWithMVC.Models.DAL.Vacation
{
    public enum ReqState
    {
        pending, approved, canceled, declined
    }

    public enum PartOfDay
    {
        all, first, second
    }

    public class VacationsModel
    {
        public int ID { get; set; }

        [Display(Name = "Part of Day ")]
        public PartOfDay day_part { get; set; }

        [Display(Name ="From Date")]
        [Required(ErrorMessage ="{0} Field is Required")]
        public DateTime fromDate { get; set; }

        [Display(Name = "To Date")]
        public DateTime? toDate { get; set; }

        [ScaffoldColumn(false)]
        [Display(Name = "Hours: ")]
        public int? hours { get; set; }

        [ScaffoldColumn(false)]
        [Display(Name = "Status")]
        public ReqState approvalstate { get; set; }

        [Display(Name = "Reason")]
        [Required(ErrorMessage = "{0} Field is Required")]
        public string message { get; set; }

        [ScaffoldColumn(false)]
        [Display(Name = "Created on")]
        public DateTime date_requested { get; set; }

        [Display(Name = "TimeOff Type")]
        [Required(ErrorMessage = "{0} Field is Required")]
        public int VacationTypeModelID { get; set; }
        public virtual VacationTypeModel vacType { get; set; }

        [Display(Name = "Employee")]
        public string ApplicationUserId { get; set; }
        public virtual ApplicationUser user { get; set; }

        public int? BranchesModelID { get; set; }
        public virtual BranchesModel assoicatedBranch { get; set; }
    }

}

JqueryDTWithMVC/Controllers/VacationsModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JqueryDTWithMVC.Models;
using JqueryDTWithMVC.Models.DAL.Vacation;
using Microsoft.AspNet.Identity;
using JqueryDTWithMVC.Models.Repository.UnitOfWork;
using JqueryDTWithMVC.Models.ViewModels.TimeOffBalance;
using static JqueryDTWithMVC.Startup;

namespace JqueryDTWithMVC.Controllers
{
    [Startup.Title(Title = "TimeOff Management")]
    public class VacationsModelsController : Controller
    {
        UnitOfWork unitOfWork = new UnitOfWork(new ApplicationDbContext());

        // GET: VacationsModels
        [Startup.Title(Title = "TimeOff Requests List")]
        [Startup.ModifiedAuthorize]
        public ActionResult Index()
        {
            var vacationsModels = new List<VacationsModel>();
            

            string userId = User.Identity.GetUserId();
            int? empBranch = unitOfWork.Users.GetUserBranch(userId);
            if (empBranch != null)
            {
                vacationsModels = unitOfWork.TimeOffs.GetTimeOffForBranch(empBranch.Value).ToList();
                if (User.IsInRole("موظف"))
                {
                    vacationsModels = vacationsModels.Where(a => a.ApplicationUserId == userId).ToList();
                }
            }

            return View(vacationsModels);
        }

        [Authorize]
        [Title(Title ="Specific User TimeOffs")]
        public ActionResult UserTimeOff(string userId)
        {
            var vacationsModels = new List<VacationsModel>();
            
            ViewBag.userId = User.Identity.GetUserId();

            vacationsModels = vacationsModels.Where(a => a.ApplicationUserId == userId).ToList();

            return View();
        }

        // GET: VacationsModels/Details/5
        [Startup.Title(Title = "TimeOff Request Details")]
        [Startup.ModifiedAuthorize]
        public ActionResult Details(int? id)
        {
            
            {
                if (!unitOfWork.TimeOffs.Any(a => a.ID == id))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var vacationModel = unitOfWork.TimeOffs.Get(id.Value);
                if (vacationModel == null)
                {
                    return HttpNotFound();
                }

                return View(vacationModel);
            }
        }

        // GET: VacationsModels/Create
        [Startup.Title(Title = "Create New TimeOff")]
        [Authorize]
        public ActionResult Create()
        {
            using (var unitOfWork = new UnitOfWork(new ApplicationDbContext()))
            {
                ViewBag.VacationTypeModelID = new SelectList(unitOfWork.TimeOffType.GetAll(), "ID", "vacationName");
                return View();
            }
        }

        // POST: VacationsModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "ID,day_part,fromDate,toDate,hours,approvalstate,message,date_requested,VacationTypeModelID,ApplicationUserId")] VacationsModel vacationsModel,
            bool fromPartial = false)
        {
            ViewBag.errorBalance = "";
            
            {
                vacationsModel.date_requested = System.DateTime.Now;
                vacationsModel.BranchesModelID = unitOfWork.Users.GetUserBranch(User.Identity.GetUserId());

                vacationsModel.toDate = vacationsModel.toDate.HasValue ? vacationsModel.toDate : vacationsModel.fromDate;

                if (vacationsModel.fromDate.Date == vacationsModel.toDate.Value.Date && vacationsModel.hours == null)
                {
                    vacationsModel.hours = vacationsModel.day_part == PartOfDay.all ? 8 : 4;
                }
                else if (vacationsModel.fromDate.Date != vacationsModel.toDate.Value.Date)
                {
                    vacationsModel.hours = (int)vacationsModel.toDate.Value.Subtract(vacationsModel.fromDate).TotalDays * 8;
                }

                // checking: 
                int currentYear = System.DateTime.Now.Year;
                int currentMonth = System.DateTime.Now.Month;
                int weekNumber = System.DateTime.Now.GetWeekOfMonth();
                string userID = User.Identity.GetUserId();

                var balance = unitOfWork.TimeOffs.GetAll().Where(aa => aa.approvalstate == Models.DAL.Vacation.ReqState.approved
                                                && aa.ApplicationUserId == userID); // get timeOff for specific users
                switch (unitOfWork.TimeOffType.Get(vacationsModel.VacationTypeModelID).policyResetEvery)
                {
                    // now filter all balances and get only the one specified in request
                    case Models.DAL.VacationType.ResetEvery.Yearly:
                        {
                            balance = balance.Where(a => a.fromDate.Year == currentYear);
                            break;
                        }
                    case Models.DAL.VacationType.ResetEvery.Monthly:
                        {
                            balance = balance.Where(a => a.fromDate.Year == currentYear && a.fromDate.Month == currentMonth);
                            break;
                        }
                    case Models.DAL.VacationType.ResetEvery.Weekly:
                        {
                            balance = balance.Where(a => a.fromDate.Year == currentYear && a.fromDate.Month == currentMonth
                                                            && a.fromDate.GetWeekOfMonth() == weekNumber);
                            break;
                        }
                }

                if (unitOfWork.TimeOffType.Get(vacationsModel.VacationTypeModelID).balance.HasValue)
                {
                    int userBalance = balance.Sum(aa => aa.hours).HasValue ? balance.Sum(aa => aa.hours).Value : 0;
                    bool error = (userBalance + vacationsModel.hours) > (unitOfWork.TimeOffType.Get(vacationsModel.VacationTypeModelID).balance * 8) ? true : false;

                    if (error)
                    {
                        ModelState.AddModelError(string.Empty, "The number of days you are trying to book exceeds available days.");
                        Startup.MiscellaneousMethod.ActionCompletionNotify("Error: The number of days you are trying to book exceeds the available days.", false);
                        return Redirect(Request.UrlReferrer.ToString());
                    }
                }
                // end of check

                if (ModelState.IsValid)
                {
                    unitOfWork.TimeOffs.Add(vacationsModel);
                    unitOfWork.Complete(true, "TimeOff Was Added Succesfully");

                    //  return RedirectToAction("Index");
                    return Redirect(Request.UrlReferrer.ToString());
                }

                ViewBag.VacationTypeModelID = new SelectList(unitOfWork.TimeOffType.GetAll(), "ID", "vacationName", vacationsModel.VacationTypeModelID);
                return View(vacationsModel);
            }
        }

        [ChildActionOnly]
        [Startup.Title(Title = "Create New TimeOff (Partial)")]
        [Authorize]
        public ActionResult CreatePartial()
        {
            
            {
                ViewBag.VacationTypeModelID = new SelectList(unitOfWork.TimeOffType.GetAll(), "ID", "vacationName");
                return PartialView();
            }
        }


        // GET: VacationsModels/Edit/5
        [Startup.Title(Title = "Edit TimeOff Request")]
        [Startup.ModifiedAuthorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            
            {
                if (!unitOfWork.TimeOffs.Any(a => a.ID == id))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var vacationModel = unitOfWork.TimeOffs.Get(id.Value);
                if (vacationModel == null)
                {
                    return HttpNotFound();
                }

                ViewBag.ApplicationUserId = User.Identity.GetUserId();
                ViewBag.VacationTypeModelID = new SelectList(unitOfWork.TimeOffType.GetAll(),
                    "ID", "vacationName", vacationModel.VacationTypeModelID);

                return View(vacationModel);
            }
        }

        // POST: VacationsModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Startup.ModifiedAuthorize]
        public ActionResult Edit([Bind(Include = "ID,day_part,fromDate,toDate,hours,approvalstate,message,date_requested,VacationTypeModelID,ApplicationUserId")] VacationsModel vacationsModel)
        {
            
            {
                if (vacationsModel.toDate == null)
                {
                    vacationsModel.toDate = vacationsModel.fromDate;
                }

                if (vacationsModel.fromDate.Date == vacationsModel.toDate.Value.Date && vacationsModel.hours == null)
                {
                    vacationsModel.hours = vacationsModel.day_part == PartOfDay.all ? 8 : 4;
                }
                else if (vacationsModel.fromDate.Date != vacationsModel.toDate.Value.Date)
                {

JqueryDTWithMVC/Views/VacationsModels/Create.cshtml
@model JqueryDTWithMVC.Models.DAL.Vacation.VacationsModel
@using Microsoft.AspNet.Identity;
@{
    ViewBag.Title = "Create New TimeOff";
    Layout = "~/Views/Shared/_HRLayout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h4 class="card-title">
            @ViewBag.Title
        </h4>
    </div>
    <div class="card-content">
        <div class="row">
            <div class="col-md-2">
                <ul class="nav nav-pills nav-pills-rose nav-stacked">
                    <li>
                        <a href="#profile" data-toggle="tab" aria-expanded="false" onclick="HideMulti(true)" id="singleTimeOffBtn">
                            Single Day
                        </a>
                    </li>
                    <li class="active">
                        <a href="#profile" data-toggle="tab" aria-expanded="true" onclick="HideMulti(false)">
                            Multiple Days
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-md-8">
                <div class="tab-content">
                    <div class="tab-pane" id="profile">
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <hr />
                                <div class="form-group">
                                    @Html.LabelFor(model => model.day_part, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EnumDropDownListFor(model => model.day_part, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.day_part, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.fromDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.fromDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                                        @Html.ValidationMessageFor(model => model.fromDate, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group" id="toDateSele">
                                    @Html.LabelFor(model => model.toDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.toDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                                        @Html.ValidationMessageFor(model => model.toDate, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group" id="hoursToggler">
                                    @Html.LabelFor(model => model.hours, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.hours, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
                                        @Html.ValidationMessageFor(model => model.hours, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.message, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.message, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.message, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.Label("Vacation Type", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.DropDownList("VacationTypeModelID", null, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.VacationTypeModelID, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <input type="hidden" name="ApplicationUserId" id="ApplicationUserId" value="@User.Identity.GetUserId()" />

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Create" class="btn btn-success" />
                                    </div>
                                </div>
                            </div>
                        }

                    </div>
                </div>
              @Html.ActionLink("Back To List", "Index", null, new { @class = "btn btn-info" })
            </div>
            
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $('#hoursToggler').hide();
        var showHours = false;
        document.getElementById('singleTimeOffBtn').click();

        function HideMulti(hideMulti) {
            if (hideMulti == true) {
                $('#toDateSele').hide();
                showHours = true;
            }
            else {
                $('#toDateSele').show();
                showHours = false;
                $('#hoursToggler').hide();
            }
        }

        $(function () {
            $("#day_part").change(function () {
                var firstDropVal = $('#day_part').val();
                if (firstDropVal != 0 && showHours) {
                    $('#hoursToggler').show();
                }
                else {
                    $('#hoursToggler').hide();
                }
            });
        });
    </script>
}

JqueryDTWithMVC/Views/VacationsModels/CreatePartial.cshtml
@model JqueryDTWithMVC.Models.DAL.Vacation.VacationsModel
@using Microsoft.AspNet.Identity;

<div class="instruction">
    <div class="row">
        <div class="col-md-2">
            <ul class="nav nav-pills nav-pills-rose nav-stacked">
                <li>
                    <a href="#profile" data-toggle="tab" aria-expanded="false" onclick="HideMulti(true)" id="singleTimeOffBtn">
                        Single Day
                    </a>
                </li>
                <li class="active">
                    <a href="#profile" data-toggle="tab" aria-expanded="true" onclick="HideMulti(false)">
                        Multiple Days
                    </a>
                </li>
            </ul>

        </div>
        <div class="col-md-8">
            <div class="tab-content">
                <div class="tab-pane" id="profile">
                    @using (Html.BeginForm("Create", "VacationsModels", FormMethod.Post, new { @id="createPartial" }))
                    {
                        <input type="hidden" name="fromPartial" id="fromPartial" value="true" />
                        @Html.AntiForgeryToken()
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.day_part, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EnumDropDownListFor(model => model.day_part, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.day_part, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.fromDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.fromDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                                    @Html.ValidationMessageFor(model => model.fromDate, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group" id="toDateSele">
                                @Html.LabelFor(model => model.toDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.toDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                                    @Html.ValidationMessageFor(model => model.toDate, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group" id="hoursToggler">
                                @Html.LabelFor(model => model.hours, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.hours, new { htmlAttributes = new { @class = "form-control", @type = "number", @Value="8", @min="0", @max="1000" } })
                                    @Html.ValidationMessageFor(model => model.hours, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.message, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.message, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.message, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("Vacation Type", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("VacationTypeModelID", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.VacationTypeModelID, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <input type="hidden" name="ApplicationUserId" id="ApplicationUserId" value="@User.Identity.GetUserId()" />
                            <div class="" id="showError" style="margin:10px 10px 10px 10px;color:red;font-size:15px">
                                @ViewBag.errorBalance
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-2">
                                    <input type="submit" value="Create" class="btn btn-success" id="btnSave" />
                                </div>
                                <div class="col-md-2">
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    }

                </div>

            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('#hoursToggler').hide();
    var showHours = false;
    document.getElementById('singleTimeOffBtn').click();

    function HideMulti(hideMulti) {
        if (hideMulti == true) {
            $('#toDateSele').hide();
            showHours = true;
            hoursToggle();
            $("#toDate").prop('required', false);
        }
        else {
            $('#toDateSele').show();
            showHours = false;
            $('#hoursToggler').hide();
            $("#toDate").prop('required', true);
        }
    }

    $(function () {
        $("#day_part").change(function () {
            hoursToggle();
        });
    });

    function hoursToggle() {
        var firstDropVal = $('#day_part').val();
        if (firstDropVal != 0 && showHours) {
            $('#hoursToggler').show();
        }
        else {
            $('#hoursToggler').hide();
        }
    }

    $('#btnSave').click(function (e) {
        var element = this;
        e.preventDefault(); // <------------------ stop default behaviour of button
        $.ajax({
            url: "/Home/EmployeeTimeOffStatus",
            type: "get",
            dataType: "json",
            traditional: true,
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                console.log(data);
                if (data != null) {
                    var seleOp = $('#VacationTypeModelID').val();
                    console.log(seleOp)
                    for (var i = 0; i < data.length; i++) {

                        if (data[i].Id == seleOp) { // if selected options and data from api matches
                            if(data[i].typelimit){
                            }
                            else{
                                data[i].typelimit = (data[i].balance+1)
                            }
                              
                            var currBala = (data[i].typelimit - data[i].balance) * 24; // in hours
                            console.log('checking: ' + data[i].typelimit + " - " + data[i].balance);
                            if (showHours) {
                                // hours
                                var hours = document.getElementById("hours").value;
                                console.log('hours and currBala : ' + currBala + " - " + hours);
                                if (currBala <= hours) {
                                    document.getElementById("showError").innerHTML = "The number of days you are trying to book exceeds available days."
                                }
                                else {
                                    $('#createPartial').submit();
                                }
                            }
                            else {
                                // toDate and fromDate
                                var fromDate = new Date(document.getElementById("fromDate").value);
                                var toDate =  new Date(document.getElementById("toDate").value)
                                console.log('hours and currBala : ' + toDate + " % " + fromDate);
                                var hours = (Math.abs(fromDate - toDate)) / (1000 * 60 * 60);;
                                console.log('hours and currBala : ' + currBala + " - " + hours);
                                if (currBala <= hours) {
                                    document.getElementById("showError").innerHTML = "The number of days you are trying to book exceeds available days."
                                }
                                else {
                                    
                                    $('#createPartial').submit();
                                }
                            }
                        }
                    }
                } else {
                    console.log("Error occurs on the Database level!");
                }
            },
            error: function () {
                console.log("An error has occured!!!");
            }
        });
    });
</script>

JqueryDTWithMVC/Views/VacationsModels/Delete.cshtml
@model JqueryDTWithMVC.Models.DAL.Vacation.VacationsModel

@{
    ViewBag.Title = "Delete TimeOff";
    Layout = "~/Views/Shared/_HRLayout.cshtml";
}


<style>
    dt dd{
        margin:10px 10px 10px 10px;
        padding: 10px 10px 10px 10px;
    }
</style>
<div class="card">
    <div class="card-header" data-background-color="green">
        <h4 class="title">@ViewBag.Title</h4>
        <p>Do you want to Delete the following TimeOff?</p>
    </div>
    <div class="card-content">
        <div>
            <dl class="dl-horizontal">
                <dt>
                    Employee Name
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.user.EmployeeName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.vacType.vacationName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.vacType.vacationName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.day_part)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.day_part)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.fromDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.fromDate)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.toDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.toDate)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.message)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.message)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-danger" /> |
                    @Html.ActionLink("Back To List", "Index", null, new { @class = "btn btn-info" })
                </div>
            }
        </div>

    </div>
</div>