JqueryDTWithMVC/Models/DAL/Settings/SettingsModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace JqueryDTWithMVC.Models.DAL.Settings
{
    public class SettingsModel
    {
        public int ID { get; set; }

        [Required]
        [StringLength(1000)]
        [Display(Name = " الاعداد")]
        public string Key { get; set; }

        [Required]
        [StringLength(1000)]
        [Display(Name = " القيمة")]
        public string Value { get; set; }
    }
}

JqueryDTWithMVC/Controllers/SettingsModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JqueryDTWithMVC.Models;
using JqueryDTWithMVC.Models.DAL.Settings;
using static JqueryDTWithMVC.Startup;
using JqueryDTWithMVC.Models.ViewModels.WSSettings;
using JqueryDTWithMVC.Helper;

namespace JqueryDTWithMVC.Controllers
{
    [Title(Title = "اعدادت الموقع")]
    public class SettingsModelsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: SettingsModels
        [Title(Title = "جدول اعدادت الموقع")]
        [AllowAnonymous]
        public ActionResult Index()
        {
            var setting = db.SettingsTable.ToArray();
            WebSiteSettingsViewModel wsSet = new WebSiteSettingsViewModel()
            {
                SITENAME = setting[0].Value,
                ADDRESS = setting[1].Value,
                TEL = setting[2].Value,
                SITE = setting[3].Value,
                EMAIL = setting[4].Value,
                LOGO = setting[5].Value,
                ALLOWTIME = setting[6].Value,
                SITEDIR = setting[7].Value
            };

            return Json(wsSet, JsonRequestBehavior.AllowGet);
        }

        // POST: SettingsModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ModifiedAuthorize]
        [Title(Title = "تعديل اعدادت الموقع")]
        public async Task<ActionResult> Edit(WebSiteSettingsViewModel settingsModel, HttpPostedFileBase setting_coClock)
        {
            if (ModelState.IsValid)
            {

                if (settingsModel.Img_Logo != null)
                {
                    if (settingsModel.Img_Logo.ContentLength > 0)
                    {
                        FileStorageClass.StoreImage(false, settingsModel.Img_Logo, "logo", Server.MapPath("/Content/css/"));
                    }
                }

                var setting = db.SettingsTable.ToArray();
                setting[0].Value = settingsModel.SITENAME;
                db.Entry(setting[0]).State = EntityState.Modified;
                await db.SaveChangesAsync();

                setting[1].Value = settingsModel.ADDRESS;
                db.Entry(setting[1]).State = EntityState.Modified;
                await db.SaveChangesAsync();

                setting[2].Value = settingsModel.TEL;
                db.Entry(setting[2]).State = EntityState.Modified;
                await db.SaveChangesAsync();

                setting[3].Value = settingsModel.SITE;
                db.Entry(setting[3]).State = EntityState.Modified;
                await db.SaveChangesAsync();

                setting[4].Value = settingsModel.EMAIL;
                db.Entry(setting[4]).State = EntityState.Modified;
                await db.SaveChangesAsync();

                setting[6].Value = settingsModel.ALLOWTIME;
                db.Entry(setting[6]).State = EntityState.Modified;
                await db.SaveChangesAsync();

                setting[7].Value = settingsModel.SITEDIR;
                db.Entry(setting[7]).State = EntityState.Modified;
                await db.SaveChangesAsync();

                return Json("done");
            }
            return Json("error");
        }

        [ModifiedAuthorize]
        [Title(Title = "تعديل شعار الموقع")]
        public ActionResult EditLogo()
        {
            return View();
        }

        [HttpPost]
        [ModifiedAuthorize]
        public ActionResult EditLogo( HttpPostedFileBase Logo)
        { 
            if (ModelState.IsValid)
            {
                if (Logo != null)
                {
                    if (Logo.ContentLength > 0)
                    {
                        FileStorageClass.StoreImage(false, Logo, "logo", Server.MapPath("/Content/SiteImage/"));
                    }
                }

                return View();
            }
            return View();
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JqueryDTWithMVC/Views/SettingsModels/Create.cshtml
@model JqueryDTWithMVC.Models.DAL.Settings.SettingsModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SettingsModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Key, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Key, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Key, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JqueryDTWithMVC/Views/SettingsModels/Delete.cshtml
@model JqueryDTWithMVC.Models.DAL.Settings.SettingsModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SettingsModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Key)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Key)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

JqueryDTWithMVC/Views/SettingsModels/Details.cshtml
@model JqueryDTWithMVC.Models.DAL.Settings.SettingsModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SettingsModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Key)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Key)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

JqueryDTWithMVC/Views/SettingsModels/Edit.cshtml
@model JqueryDTWithMVC.Models.DAL.Settings.SettingsModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SettingsModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Key, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Key, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Key, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JqueryDTWithMVC/Views/SettingsModels/EditLogo.cshtml
@{
    ViewBag.Title = "EditLogo";
}

<h2 style="margin-top:1%;margin-right:1%">تعديل الشعار</h2>
@using (Html.BeginForm("EditLogo", "SettingsModels", FormMethod.Post ,new { enctype = "multipart/form-data" }))
{
    <div class="row" style="font-size:16px;font-weight:600;margin-top:3%">
        <div class="col-md-1">
            <label for="file" >صورة الشعار: </label>
        </div>
        <div class="col-md-2">
            <input type="file" name="Logo" accept="image/x-png, image/gif, image/jpeg" id="Logo" />
        </div>
        <div class="col-md-2">
            <input type="submit" class="form-control" value="ارسال الشعار" />
        </div>
    </div>
}

JqueryDTWithMVC/Views/SettingsModels/Index.cshtml
@model IEnumerable<JqueryDTWithMVC.Models.DAL.Settings.SettingsModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Key)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Value)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Key)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Value)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>