JqueryDTWithMVC/Models/DAL/Documents/DocumentsModels.cs
using JqueryDTWithMVC.Models.DAL.DocumentsCategory;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
 

namespace JqueryDTWithMVC.Models.DAL.Documents
{
    public class DocumentsModels
    {
        public int ID { get; set; }

        [Display(Name = "Document Path")]
        [MaxLength(100, ErrorMessage = "{0} Field cann't be larger than 100 Character")]
        [MinLength(1, ErrorMessage = "{0} Field cann't be smaller than 1 Character")]
        public string filePath { get; set; }

        [Display(Name = "Document Name")]
        [MaxLength(100, ErrorMessage = "{0} Field cann't be larger than 100 Character")]
        [MinLength(1, ErrorMessage = "{0} Field cann't be smaller than 1 Character")]
        public string fileName { get; set; }

        public int DocumentsCategoryModelsID { get; set; }
        public virtual DocumentsCategoryModels documentCatgeory { get; set; }

        public virtual List<DocumentsWithUsersModels> sharedWithUsers { get; set; }
    }
}

JqueryDTWithMVC/Controllers/DocumentsModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JqueryDTWithMVC.Models;
using JqueryDTWithMVC.Models.DAL.Documents;
using JqueryDTWithMVC.Models.ViewModels.Documents;
using JqueryDTWithMVC.Models.Repository.UnitOfWork;
using static JqueryDTWithMVC.Startup;
using Microsoft.AspNet.Identity;

namespace JqueryDTWithMVC.Controllers
{
    [Title(Title = "Manage Documents")]
    public class DocumentsModelsController : Controller
    {
        UnitOfWork unitOfWork = new UnitOfWork(new ApplicationDbContext());

        // GET: DocumentsModels
        // GET: DocumentsModels
        [Title(Title = "Uploaded Documents List")]
        public ActionResult Index()
        {
            int bInt = unitOfWork.Branches.getUserBranch(User.Identity.GetUserId());
            var res = unitOfWork.Documents.GetAll().Where(aa => aa.sharedWithUsers != null ? (aa.sharedWithUsers.Any(bb => bb.users.BranchesModelID.HasValue ? bb.users.BranchesModelID.Value == bInt : false)) : false);
            var userId = User.Identity.GetUserId();

            if (User.IsInRole("موظف"))
                res = res.Where(a => a.sharedWithUsers!= null ? a.sharedWithUsers.Any(aa => aa.ApplicationUserId == userId) : false);

            return View(res);
        }

        [Title(Title = "Uploaded Documents List For User")]
        public ActionResult UserDocuments(string userId)
        {
            var res = unitOfWork.Documents.GetAll();
            var uId = String.IsNullOrEmpty(userId) ? User.Identity.GetUserId() : userId;
            ViewBag.userId = userId;

            if (User.IsInRole("موظف"))
                res = res.Where(a => a.sharedWithUsers != null ? a.sharedWithUsers.Any(aa => aa.ApplicationUserId == uId) : false);

            return View(res);
        }

        // GET: DocumentsModels/Details/5
        [Title(Title = "Uploaded Document Details")]
        public ActionResult Details(int? id)
        {
            if (!unitOfWork.Documents.Any(a => a.ID == id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var documentsModels = unitOfWork.Documents.Get(id.Value);
            if (documentsModels == null)
            {
                return HttpNotFound();
            }

            return View(documentsModels);
        }

        // GET: DocumentsModels/Create
        [Title(Title = "Upload New Document")]
        public ActionResult Create()
        {
            int bInt = unitOfWork.Branches.getUserBranch(User.Identity.GetUserId());
            ViewBag.DocumentsCategoryModelsID = new SelectList(unitOfWork.DocumentsCategory.GetAll(), "ID", "catgeoryName");
            ViewBag.associatedUsers = new SelectList(unitOfWork.Users.GetAll().Where(aa => aa.BranchesModelID.HasValue ? aa.BranchesModelID.Value == bInt : false), "Id", "EmployeeName");

            return View();
        }

        // POST: DocumentsModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,uploadedFile,sharedWithUsers,DocumentsCategoryModelsID")]
                                DocumentsViewModel documentsViewModels)
        {
            if (ModelState.IsValid)
            {
                documentsViewModels.sharedWithUsers = documentsViewModels.sharedWithUsers.Concat(new string[] { User.Identity.GetUserId()}).ToArray();
                var res = unitOfWork.Documents.ToModel(documentsViewModels);

                unitOfWork.Documents.Add(res.Item1);
                unitOfWork.Complete();

                JqueryDTWithMVC.Helper.FileStorageClass.StoreFile(documentsViewModels.uploadedFile, Server.MapPath("~/Content/EmployeeFiles/"));

                // add users to document exist
                if (documentsViewModels.sharedWithUsers != null)
                {
                    for (int i = 0; i < res.Item2.Length; i++)
                    {
                        unitOfWork.Documents.AddUserShare(unitOfWork.Documents.Find(a => a.fileName == documentsViewModels.uploadedFile.FileName)
                            .OrderByDescending(a => a.ID).First().ID // get the last file added by this name
                            , res.Item2[i]);
                        unitOfWork.Complete();
                    }
                }

                return Redirect(Request.UrlReferrer.ToString());
            }

            int bInt = unitOfWork.Branches.getUserBranch(User.Identity.GetUserId());
            ViewBag.DocumentsCategoryModelsID = new SelectList(unitOfWork.DocumentsCategory.GetAll(), "ID", "catgeoryName",
                documentsViewModels.DocumentsCategoryModelsID);
            ViewBag.associatedUsers = new SelectList(unitOfWork.Users.GetAll().Where(aa => aa.BranchesModelID.HasValue ? aa.BranchesModelID.Value == bInt : false), "Id", "EmployeeName");
            return View(documentsViewModels);
        }

        [ChildActionOnly]
        public ActionResult CreatePartial()
        {
            var bId = unitOfWork.Branches.getUserBranch(User.Identity.GetUserId());

            ViewBag.DocumentsCategoryModelsID = new SelectList(unitOfWork.DocumentsCategory.GetAll(), "ID", "catgeoryName");
            ViewBag.associatedUsers = new SelectList(unitOfWork.Users.GetAll().Where(aa => aa.BranchesModelID.HasValue ? aa.BranchesModelID.Value == bId : false), "Id", "EmployeeName");

            return PartialView();
        }

        // GET: DocumentsModels/Edit/5
        [Title(Title = "Edit Uploaded Document Informations")]
        [ModifiedAuthorize]
        public ActionResult Edit(int? id)
        {
            {
                if (!unitOfWork.Documents.Any(a => a.ID == id))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var documentModel = unitOfWork.Documents.Get(id.Value);
                if (documentModel == null)
                {
                    return HttpNotFound();
                }

                int bInt = unitOfWork.Branches.getUserBranch(User.Identity.GetUserId());
                ViewBag.DocumentsCategoryModelsID = new SelectList(unitOfWork.DocumentsCategory.GetAll(), "ID", "catgeoryName",
                    documentModel.DocumentsCategoryModelsID);
                ViewBag.associatedUsers = new SelectList(unitOfWork.Users.GetAll().Where(aa => aa.BranchesModelID.HasValue ? aa.BranchesModelID.Value == bInt : false), "Id", "EmployeeName");

                var docViewModel = new DocumentsViewModel()
                {
                    DocumentsCategoryModelsID = documentModel.DocumentsCategoryModelsID,
                    users = documentModel.sharedWithUsers
                };
                return View(docViewModel);
            }
        }

        // POST: DocumentsModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ModifiedAuthorize]
        public ActionResult Edit([Bind(Include = "ID,sharedWithUsers,uploadedFile,DocumentsCategoryModelsID")] DocumentsViewModel documentsViewModels)
        {
            if (ModelState.IsValid)
            {
                documentsViewModels.sharedWithUsers = documentsViewModels.sharedWithUsers.Concat(new string[] { User.Identity.GetUserId() }).ToArray();
                unitOfWork.Documents.UpdateDocument(documentsViewModels);

                JqueryDTWithMVC.Helper.FileStorageClass.StoreFile(documentsViewModels.uploadedFile, Server.MapPath("~/Content/EmployeeFiles/"));

                unitOfWork.Complete();
                return RedirectToAction("Index");
            }

            int bInt = unitOfWork.Branches.getUserBranch(User.Identity.GetUserId());
            ViewBag.DocumentsCategoryModelsID = new SelectList(unitOfWork.DocumentsCategory.GetAll(), "ID", "catgeoryName",
                documentsViewModels.DocumentsCategoryModelsID);
            ViewBag.associatedUsers = new SelectList(unitOfWork.Users.GetAll(), "Id", "EmployeeName");

            return View(documentsViewModels);
        }

        // GET: DocumentsModels/Delete/5
        [Title(Title = "Delete Uploaded Document")]
        [ModifiedAuthorize]
        public ActionResult Delete(int? id)
        {
            if (!unitOfWork.Documents.Any(a => a.ID == id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var documentsModels = unitOfWork.Documents.Get(id.Value);
            if (documentsModels == null)
            {
                return HttpNotFound();
            }

            return View(documentsModels);
        }

        // POST: DocumentsModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [ModifiedAuthorize]
        [Title(Title = "Delete Uploaded Document Information")]
        public ActionResult DeleteConfirmed(int id)
        {
            unitOfWork.Documents.RemoveDocument(id);
            unitOfWork.Complete();

            return RedirectToAction("Index");
        }
    }
}

JqueryDTWithMVC/Views/DocumentsModels/Create.cshtml
@model JqueryDTWithMVC.Models.ViewModels.Documents.DocumentsViewModel

@{
    ViewBag.Title = "Add New Document";
    Layout = "~/Views/Shared/_HRLayout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h4 class="card-title">
            @ViewBag.Title
        </h4>
    </div>
    <div class="card-content">
        @using (Html.BeginForm("Create", "DocumentsModels", FormMethod.Post, new { @enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <h4>Fill the Following Informations</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.uploadedFile, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" name="uploadedFile" id="uploadedFile" required style="opacity:unset;position:unset;" />
                        @Html.ValidationMessageFor(model => model.uploadedFile, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="select-employee" class="control-label col-md-2">Team Members</label>
                    <div class="col-md-10">
                        <select id="se_employee" name="sharedWithUsers[]" multiple class="demo-default" style="width:70%" placeholder="Select an Employee...">
                            <option value="">Select an Employee...</option>
                            @foreach (var user in (SelectList)ViewBag.associatedUsers)
                            {
                                <option value="@user.Value">@user.Text</option>
                            }
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Document Category", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("DocumentsCategoryModelsID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.DocumentsCategoryModelsID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back To List", "Index", null, new { @class = "btn btn-info" })
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $('#se_employee').selectize({
        });
    </script>
}

JqueryDTWithMVC/Views/DocumentsModels/CreatePartial.cshtml
@model JqueryDTWithMVC.Models.ViewModels.Documents.DocumentsViewModel
@using Microsoft.AspNet.Identity;


<link href="~/Content/selectize/selectize.bootstrap3.css" rel="stylesheet" />
@using (Html.BeginForm("Create", "DocumentsModels", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h6>Fill the Following Informations</h6>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.uploadedFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="uploadedFile" id="uploadedFile" required style="opacity:unset;position:unset;" />
                @Html.ValidationMessageFor(model => model.uploadedFile, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label for="select-employee" class="control-label col-md-2">Team Members</label>
            <div class="col-md-10">
                <select id="selectedEmployee" name="sharedWithUsers[]" multiple class="demo-default" style="width:70%" placeholder="Select an Employee...">
                    <option value="">Select an Employee...</option>
                    @foreach (var user in (SelectList)ViewBag.associatedUsers)
                    {
                        <option value="@user.Value">@user.Text</option>
                    }
                </select>
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Document Category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DocumentsCategoryModelsID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DocumentsCategoryModelsID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")
<script src="~/Content/selectize/selectize.js"></script>
<script>
    $('#selectedEmployee').selectize({
    });
</script>

JqueryDTWithMVC/Views/DocumentsModels/Delete.cshtml
@model JqueryDTWithMVC.Models.DAL.Documents.DocumentsModels

@{
    ViewBag.Title = "Delete Document";
    Layout = "~/Views/Shared/_HRLayout.cshtml";
}
<div class="card">
    <div class="card-header">
        <h4 class="card-title">
            @ViewBag.Title
        </h4>
    </div>
    <div class="card-content">
        <h3>Do you want to remove this uploaded document?</h3>
        <div>
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.documentCatgeory.catgeoryName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.documentCatgeory.catgeoryName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.filePath)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.filePath)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.fileName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.fileName)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-danger" /> |
                    @Html.ActionLink("Back To List", "Index", null, new { @class = "btn btn-info" })
                </div>
            }
        </div>
    </div>
</div>

JqueryDTWithMVC/Views/DocumentsModels/Details.cshtml
@model JqueryDTWithMVC.Models.DAL.Documents.DocumentsModels

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_HRLayout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h4 class="card-title">
            @ViewBag.Title
        </h4>
    </div>
    <div class="card-content">
        <div>
            <h4>Document Informations</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.documentCatgeory.catgeoryName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.documentCatgeory.catgeoryName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.filePath)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.filePath)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.fileName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.fileName)
                </dd>

            </dl>
        </div>
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.ID }, new { @class = "btn btn-warning" }) |
            @Html.ActionLink("Back To List", "Index", null, new { @class = "btn btn-info" })
        </p>
    </div>
</div>

JqueryDTWithMVC/Views/DocumentsModels/Edit.cshtml
@model JqueryDTWithMVC.Models.ViewModels.Documents.DocumentsViewModel

@{
    ViewBag.Title = "Edit Uploaded Document";
    Layout = "~/Views/Shared/_HRLayout.cshtml";
}
<link href="~/Content/selectize/selectize.bootstrap3.css" rel="stylesheet" />

<div class="card">
    <div class="card-header">
        <h4 class="card-title">
            @ViewBag.Title
        </h4>
    </div>
    <div class="card-content">
        @using (Html.BeginForm("Edit", "DocumentsModels", FormMethod.Post, new { @enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Edit the Following Informations:</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.ID)
                <div class="form-group">
                    @Html.LabelFor(model => model.uploadedFile, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" name="uploadedFile" id="uploadedFile" style="opacity:unset;position:unset;" />
                        @Html.ValidationMessageFor(model => model.uploadedFile, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="select-employee" class="control-label col-md-2">Team Members</label>
                    <div class="col-md-10">
                        <select id="select-employee" name="sharedWithUsers[]" multiple class="demo-default" style="width:70%" placeholder="Select an Employee...">
                            <option value="">Select an Employee...</option>
                            @foreach (var user in (SelectList)ViewBag.associatedUsers)
                            {
                                if (Model.users != null)
                                {
                                    if (Model.users.Any(aa => aa.ApplicationUserId == user.Value))
                                    {
                                        <option value="@user.Value" selected>@user.Text</option>
                                    }
                                }
                                else
                                {
                                    <option value="@user.Value">@user.Text</option>
                                }
                            }
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Document Category", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("DocumentsCategoryModelsID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.DocumentsCategoryModelsID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <input type="hidden" name="sharedWithUsers" id="sharedWithUsers" value="" />
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Edit" class="btn btn-warning" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back To List", "Index", null, new { @class = "btn btn-info" })
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Content/selectize/selectize.js"></script>
    <script>
        $('#select-employee').selectize({
        });
    </script>
}

JqueryDTWithMVC/Views/DocumentsModels/Index.cshtml
@model IEnumerable<JqueryDTWithMVC.Models.DAL.Documents.DocumentsModels>

@{
    ViewBag.Title = "Documents List";
    Layout = "~/Views/Shared/_HRLayout.cshtml";
}


<div class="card">
    <div class="card-header">
        <h4 class="card-title">
            @ViewBag.Title
        </h4>
    </div>
    <div class="card-content" style="font-size:13px !important;">
        <p>
            @Html.ActionLink("Add New Document", "Create", null, new { @class = "btn btn-success" })
        </p>
        <table class="table table-responsive">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.documentCatgeory.catgeoryName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.fileName)
                </th>
                <th>
                    Users
                </th>
                <th>Actions</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.documentCatgeory.catgeoryName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fileName)
                    </td>
                    <td>
                        @if (item.sharedWithUsers != null)
                        {
                            foreach (var i in item.sharedWithUsers)
                            {
                                <p>@i.users.EmployeeName</p>
                            }
                        }

                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "btn btn-warning" }) |
                        @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "btn btn-info" }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "btn btn-danger" }) |
                        <a href="@item.filePath" class="btn btn-default"> Download</a>
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

JqueryDTWithMVC/Views/DocumentsModels/UserDocuments.cshtml
@model IEnumerable<JqueryDTWithMVC.Models.DAL.Documents.DocumentsModels>
@{
    ViewBag.Title = "User Documents Lists";
    Layout = "~/Views/Shared/_ProfileLayout.cshtml";
}
<p>
    @Html.ActionLink("Add New Document", "Create", null, new { @class = "btn btn-success" })
</p>
<table class="table table-responsive">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.documentCatgeory.catgeoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fileName)
        </th>
        <th>
            Users
        </th>
        <th>
            Actions
        </th>
    </tr>

    @foreach (var item in Model)
            {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.documentCatgeory.catgeoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fileName)
            </td>
            <td>
                @if (item.sharedWithUsers != null)
                {
                    foreach (var i in item.sharedWithUsers)
                    {
                        <p>@i.users.EmployeeName</p>
                    }
                }
            </td>
            <td>
                <a href="/DocumentsModels/Edit?id=@item.ID" class="btn btn-just-icon btn-simple btn-twitter">
                    <i class="fa fa-edit"></i>
                    <div class="ripple-container"></div>
                </a> |
                <a href="/DocumentsModels/Delete?id=@item.ID" class="btn btn-just-icon btn-simple btn-twitter">
                    <i class="fa fa-close"></i>
                    <div class="ripple-container"></div>
                </a> |
                <a href="@item.filePath" class="btn btn-just-icon btn-simple btn-twitter">
                    <i class="fa fa-download"></i>
                    <div class="ripple-container"></div>
                </a>
            </td>
        </tr>
    }

</table>